---
- hosts: all
  become: yes
  gather_facts: False
  pre_tasks:
    - name: Ansible | Install Python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

  roles:
    - { role: EDITTHIS }
